// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structs} from '../models';

export function SearchPokemon(arg1:string):Promise<structs.Pokemon>;
